# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ad49c6c9fc0fb9067d4a66e06456f1e54fc9382292e1a03cf606b4cb2c16d939781091efffa4627ec288a60f580c5870aeae8cf71392c89c28caf3bb9ada762

test:
  secret_key_base: 29c20735e3ad026fa581c71961c5c74bb2fce6e87374460e01fbab3209a233d6604e62a7c3ab8383122019681bb82d8b3e0e39a4bf7dc0d70bae268fff7568e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
